name: Deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to docker
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin docker.io
      
      - name: Set Docker Buildkit
        run: export DOCKER_BUILTKIT=1
      
      - name: Build and Push Docker Image
        run: | 
          docker build -t ${{ secrets.REGISTRY_USER }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} .
          docker push ${{ secrets.REGISTRY_USER }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
      
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Install SSH client
        run: sudo apt-get install openssh-client
      
      - name: Create SSH Key
        run: |
          echo "${{ secrets.SSH_KEY }}" > key
          chmod 400 key
      
      - name: Deploy to GCP
        run: |
          ssh -o StrictHostKeyChecking=no -i key ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_STATIC_IP }} "
            sudo docker container stop ${{ secrets.CONTAINER_NAME }} || true;
            sudo docker container rm -f ${{ secrets.CONTAINER_NAME }} || true;
            sudo docker image rm -f ${{ secrets.REGISTRY_USER }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} || true;
            sudo docker run --name ${{ secrets.CONTAINER_NAME }} -d -p 80:8000 ${{ secrets.REGISTRY_USER }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}"
